// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT1tCjyEf83-sFHdj91XfG-eCGV46Q8uw',
    appId: '1:1025532827951:android:b0392c02b7c513237ea9da',
    messagingSenderId: '1025532827951',
    projectId: 'vs-droid',
    storageBucket: 'vs-droid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALBNMpY-WkG_OX5lvwsta-eNs1G81wfvk',
    appId: '1:1025532827951:ios:69bc53bdbf5518fe7ea9da',
    messagingSenderId: '1025532827951',
    projectId: 'vs-droid',
    storageBucket: 'vs-droid.appspot.com',
    iosClientId: '1025532827951-smm2depfpvarlj29j9e9jcsdsfh9gi5m.apps.googleusercontent.com',
    iosBundleId: 'com.deskbtm.vsDroid',
  );
}
